---
- name: RPM | Determine if firewalld installed
  command: "rpm -q firewalld"
  register: s
  changed_when: false
  failed_when: false
  always_run: yes

- name: Set the has_firewalld fact
  set_fact:
    has_firewalld: "{{ s.rc == 0 }}"

- name: Determine if iptables-services installed
  command: "rpm -q iptables-services"
  register: s
  changed_when: false
  failed_when: false
  always_run: yes

- name: Set the has_iptables fact
  set_fact:
    has_iptables: "{{ s.rc == 0 }}"
